### ISSUE TITLE
Go executable available after build?

### ISSUE THREAD

**Issue by ecordell** [heroku/heroku-buildpack-go#104]
It would be useful to have the `go` command available after the compile step for running management commands (with `go run`). 

Is there any reason it's not currently available? I see that it is installed in `${build_dir}/.heroku/go`, but `${build_dir}/.heroku` is removed after compiling.

**Comment by kr** [comment]
This is a tough call. My two cents:

I agree it's useful to be able to 'go run' things in the app. On the other hand, the slug would be bigger if it included the compiler and standard library. The common case is starting ordinary dynos that don't need the compiler, and a larger slug makes dynos take longer to start up.

I'm not sure if it's worth making that common operation slower for the benefit of running management commands, especially since you can still run those management commands on other systems such as your laptop (possibly after first loading environment variables from the app's config). On the other hand, sometimes there's a significant advantage to running management processes in a dyno inside AWS with fast network RTT to the other services such as a database. This can mean the difference between minutes and hours for some tasks.

Here's a possible alternative. The buildpack could include a shell script to install the go compiler. It could install this script into the slug filesystem as a command like 'get-go-compiler'. That way, ordinary dynos wouldn't have to suffer the overhead of including the whole go compiler, and one-off dynos can still use the compiler with `heroku run get-go-compiler '&&' go run foo.go`. If we wanted to get fancy, this shell script could be installed under the name `go` and it could install the compiler on demand, otherwise transparently invoking the go tool. Then the usage would be easier, `heroku run go run foo.go`. I'd write a patch for this if other folks think it's a good idea.

**Comment by freeformz** [comment]
To even make this useful the slug's directories would need to be a proper Go workspace. This is the way the docker image works right now and I'm been thinking of aligning them.

@ecordell What are your use cases for having go available in the slug?

**Comment by freeformz** [comment]
Closing as it's been here for a long time w/o response.
