### ISSUE TITLE
Plain /vendor folder support

### ISSUE THREAD

**Issue by paganotoni** [heroku/heroku-buildpack-go#114]
First of all thanks for all the effort building this buildpack to make heroku support Go.
is there a reason why this buildpack does not support a simple /vendor folder + GO15VENDOREXPERIMENT=1?.

Regards!

**Comment by freeformz** [comment]
1. the `$GO15VENDOREXPERIMENT` env var (nor is `$GOVERSION` ) isn't available at detection time.
2. `vendor/` is present in may ruby apps (maybe others) so there would be a detection conflict if we just detected the directory.
3. We need to know the appropriate directory to place your go code into during compilation, so that packages that are self referential compile correctly. I have an idea about how to work around this issue though, just haven't had the time to code it up and test it.
4. I feel it's probably better to support different tools and their detection via the meta-data files they create. This way as the tools change/mature the buildpack can DTRT wrt how these tools work.
5. I am hesitant to solve any of these issues in a haphazard way as I'll have to support them for a long time.

PS: Please don't hand maintain `vendor/`, use a tool.

**Comment by freeformz** [comment]
With that said, I do plan on supporting glide and govendor. ATM you could use those tools and fake things out by creating a `Godeps/Godeps.json` file with these minimal contents:

``` json
{
    "ImportPath": "$the-root-package path of your app, e.g. github.com/heroku/go-getting-started",
    "GoVersion": "go1.6",
    "Packages": [
        "$pkg spec to pass to go install. probably `.` (default if missing) or `./cmd/...` or `./...`"
    ]
}
```

**Comment by paganotoni** [comment]
@freeformz thanks for taking time to explain this to me, i will follow your advise and use something like glide or govendor, much appreciated!

**Comment by freeformz** [comment]
Great. Please open a support ticket if you have any issues, have support escalate to me if they tell you glide / govendor aren't supported and I'll take a look. I'll also keep your info handy if you are interested in trying out a new branch supporting your tool when it's ready.

**Comment by freeformz** [comment]
@apaganobeleno FYI: This is basically unsupported ATM, but there is this as well: https://github.com/heroku/heroku-buildpack-go/compare/govendor?w=1

I'm not sure I like having to add the build stuff to `vendor.json` though.
