### ISSUE TITLE
go command not available during release phase

### ISSUE THREAD

**Issue by goenning** [heroku/heroku-buildpack-go#169]
Hi,

I'd like to run some `go` commands during `release` phase, but it doesn't seem to be available. Is there something I need/can do?

My Procfile:
```
release: make migrate
web: make run
```

My Makefile:
```
...
migrate:
	go get -u github.com/mattes/migrate
	migrate -url ${DATABASE_URL} -path ./db/migrations up

run:
	./wchy-api
...
```
> 2017-01-18T21:40:58.931330+00:00 app[release.6583]: go get -u github.com/mattes/migrate
> 2017-01-18T21:40:58.931433+00:00 app[release.6583]: make: go: Command not found

**Comment by freeformz** [comment]
It's not really documented because it's currently only used for the test pack stuff and I may change the "interface" long term, but you can set `GO_INSTALL_TOOLS_IN_IMAGE` to `true` (`heroku config:set GO_INSTALL_TOOLS_IN_IMAGE=true`) to setup the go tool chain into the resulting slug. Note, this increases your slug size and dyno boot times a bit.

Additionally the app can be laid out inside of a `$GOPATH` when `GO_SETUP_GOPATH_IN_IMAGE` is set to `true`, which may be required depending on what you are running during release phase.

After setting these config variables you will need to push your code again.

**Comment by freeformz** [comment]
With that said I usually recommend vendoring migrate and telling the buildpack to install that package as well. This sidesteps needing the go tool change in your slug. What vendoring tool are you using?

**Comment by goenning** [comment]
govendor. I'm not sure how to do what you said, can you provide me more information/docs? Thanks

EDIT: sorry, I didn't see your first comment. I'll try it out.

**Comment by goenning** [comment]
It worked after setting both env variables, thanks! 

But how do you `telling the buildpack to install that package as well`? I'd like to keep the slug without the `go` if that's not a standard.

**Comment by freeformz** [comment]
Sorry about the late response. For govendor if you want to vendor migrate run `govendor fetch github.com/mattes/migrate` and in `vendor/vendor.json` add an element to the `heroku.install`  (or create it) array. This is called out in [this](https://devcenter.heroku.com/articles/go-support#vendoring-additional-main-packages) devcenter article.
