### ISSUE TITLE
add `go generate` stage

### ISSUE THREAD

**Issue by posener** [heroku/heroku-buildpack-go#203]
Currently I must run the go generate on my machine and commit the changed files to github.
Can you add a go generate command before the go install that will do this as part of the build process?

**Comment by freeformz** [comment]
The problem with I see with a `go generate` stage are:

1. determining when it should be run.
1. A given random `go generate` run may also require additional local dependencies that aren't checked into source control because of size, legal requirements, etc.
1. What if the generated code has different dependencies then the rest of the pushed code? What is the right thing to do then?

**Comment by posener** [comment]
Hi,
I had an issue with a go bindata which was large enough to be inconvenient to be checked in to the source control and a go generate command before the build would be much of help.
I understand your points, and I don't need anymore this change, so I'm closing the issue.
Thanks!
