### ISSUE TITLE
Support github.com/wallester/migrate

### ISSUE THREAD

**Issue by gaffneyc** [heroku/heroku-buildpack-go#223]
We're using [wellester/migrate](https://github.com/wallester/migrate) for migrations and would love to see it supported in the official tooling. We choose it over mattes/migrate because we found the story around installing v3 to be a pain locally for development.

I originally tried adding it in `additional-tools` as I figured it would be anything that you can `go get` and was surprised to then read it was hard coded to only support mattes/migrate. Extending `additional-tools` to run a `go get` on anything passed in might be a good solve for this as well.

**Comment by freeformz** [comment]
mattes/migrate can't be go gotten in a sane way (at least the last time I looked). We also have requirements around tracking the source and versions of what is built that a `go get` can't satisfy (it just gets whatever is on master).

With that said there are two options ....

1. vendor github.com/wellester/migrate and then add it to the `install` list.
2. Wait for it to be added to additional tools. I'm not even sure I would because AFAICT it's vendorable, but I'll have to explore the tool more.

**Comment by gaffneyc** [comment]
What we did was to vendor it and then copy and paste the code for the migrate binary into `cmd/migrate`. This is working for us right now though it's not perfect. Adding it to the install list instead is interesting and I'll have to look at that.

You bring up an interesting point that wellester/migrate is easily vendorable but what does that mean for future additions to `additional-tools`? Will any new additions be limited apps that are hard to install? Would it make sense to instead have a heroku buildpack that installs mattes/migrate?

**Comment by freeformz** [comment]
Using a separate buildpack to install mattes/migrate makes sense, but it's a lot of work. Since mattes/migrate has a fair bit of usage it seemed like adding support for it in the buildpack was a better idea than having to force people to add a different buildpack in the right order to just get mattes/migrate. A future iteration/improvement around mattes/migrate may be to detect it's needed and just install it automatically. That is more work (and may not be possible, I haven't dug into it) and I wanted to allow people to opt in to having mattes/migrate with as little fuss as possible, sooner than later, so came up with "additional-tools".

Note: It used to be somewhat trivial, if perhaps a bit annoying because of the added dependencies, to vendor mattes/migrate and add it to the `install` list. This is still my recommendation for other tools, like wellester/migrate. The steps would be (assuming `govendor`):

1. `govendor fetch github.com/wallester/migrate`
1. edit `vendor/vendor.json` and make sure `heroku.install` contains `github.com/wallester/migrate` (and probably either `.` or `./cmd/...` or `./...` depending on the structure of your application.
1. `git commit -avm "Vendor wallester/migrate"`
1. `git push heroku master`
