### ISSUE TITLE
error when trying to use the latest release of go with modules

### ISSUE THREAD

**Issue by kr** [heroku/heroku-buildpack-go#266]
The readme for module mode says "If not specified defaults to the most recent supported version of Go."

I tried to deploy an app this way, but got an error message:

```
remote: -----> Go app detected
remote:  !!    
remote:  !!    Go modules are an experimental feature of go1.11
remote:  !!    Any issues building code that uses Go modules should be
remote:  !!    reported via: https://github.com/heroku/heroku-buildpack-go/issues
remote:  !!    
remote:  !!    Additional documentation for using Go modules with this buildpac
remote:  !!    can be found here: https://github.com/heroku/heroku-buildpack-go#go-module-specifics
remote:  !!    
remote:  !!    You are using , which does not support the Go modules experiment
remote:  !!    
remote:  !!    Please add the following comment to your go.mod file to specify go1.11:
remote:  !!    // +heroku goVersion go1.11
remote:  !!    
remote:  !!    Then commit and push again.
```

I can prepare a reduced testcase if that would help.

**Comment by freeformz** [comment]
Go 1.11 is the most recent supported version of Go on Heroku, but it's not the default (yet). The buildpack actually uses it's [DefaultVersion](https://github.com/heroku/heroku-buildpack-go/blob/2cb93b701700ce578d14e32119b015449e663360/data.json#L4), which has almost always been the most recent version, but it doesn't have to be.

I'm going to change the text in the readme to be more accurate.

I am also concerned that your output says:
`You are using , which`, instead of `You are using go1.10.4, which....`

AFAICT it shouldn't. :-(

**Comment by freeformz** [comment]
And I realize why that's happening too.

**Comment by freeformz** [comment]
As an alternative, we could default to go1.11 if go.mod is detected, but my gut reaction to that is -1.

**Comment by freeformz** [comment]
I changed my mind. go.mod w/o a version == go1.11 for now.
