### ISSUE TITLE
buildpack: release fails with modules + GO_GIT_CRED

### ISSUE THREAD

**Issue by arxdsilva** [heroku/heroku-buildpack-go#289]
Hi, 

Im trying to release an app to Heroku but the release phase fails when I try to install a migration tool (gomod tries to install dependencies), so It isnt using the `GO_GIT_CRED__{protcol}__{host}` env. It builds properly with the env but the release doesnt.

Is it possible to enable on this new activity? Where can I see the possible envs for each phase?

**Comment by freeformz** [comment]
The buildpack isn't run during release phase, nor is anything provided by the buildpack available during release phase, just the output of the buildpack (built code).

My suggestion is to compile everything you need during build time and run the compiled programs necessary at release phase time.

Do you have a support ticket I can refer to?

**Comment by arxdsilva** [comment]
Hi @freeformz thanks for the fast response. I didnt open any ticket, sorry about that. I suppose that It's faster if I just use the `go mod vendor` command instead of customizing my own buildpack. But I'm open to suggestions :D

**Comment by freeformz** [comment]
@arxdsilva If you open a support ticket, indicate what you are trying to do, give permission to access the app and ask that it be escalated to me I can take a look and get more context quickly then going back on forth in a public forum.

Otherwise....
Install the migration tool at build time and it will be available during release phase.

**Comment by freeformz** [comment]
I believe this is fixed now.
