### ISSUE TITLE
Ignore vendoring in Go 1.14

### ISSUE THREAD

**Issue by codedius** [heroku/heroku-buildpack-go#394]
Hi! I'm trying to build my app with Go 1.14, but faces the error:

> [module name] explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory

Is there any way to ignore Go vendoring in Heroku? I've tried use env GOFLAGS=-mod=mod but it didn't work.

**Comment by LaysDragon** [comment]
I face the same problem while using gitlab auto devops 
need to find a way to get it use the go mod instead vendor

**Comment by danp** [comment]
Hi there,

It sounds possible that `go mod vendor` hasn't been run locally with go1.14 yet. Could either of you please share the output of `go version` and `go env` from a project having this issue?

If I understand correctly, something like this might fix it:

1. Be sure `go version` reports go1.14 or greater
2. Within your project, run `go mod vendor`
3. Commit any changes, such as lines added to `vendor/modules.txt` prefixed with `#`
4. `git push heroku master` or similar

Thanks!

**Comment by codedius** [comment]
Hi @danp,

Please, read the first message carefully. **WITH** vendoring everything works fine, but I'm interested in how to use Go 1.14 in Heroku **WITHOUT** vendoring. In simple words, I **don't want** to use `go mod vendor`, but I **have to**, because I get the error above otherwise. So, is there any way to ignore Go vendoring in Heroku?

**Comment by danp** [comment]
Hi, sorry for misunderstanding. I could still use some info about the project you're working with to make a better recommendation. In addition to the info I asked for above, could you please provide the output of `ls -la vendor/modules.txt`?

Thanks!

**Comment by codedius** [comment]
Ok, so:

1. `go version go1.14 darwin/amd64`
2. Done
3. Done
4. Done

Output:
`-rw-r--r--  1 lepeshev  staff  2560 Mar 12 18:52 vendor/modules.txt`

**Comment by danp** [comment]
Thanks! How about `go env` output?

I'm also wondering if you have a line in `go.mod` that starts with `go` and what it says. If it doesn't say `go 1.14`, please update it and try the `go mod vendor` and following steps again.

In the meantime, I'll see if I can put together something that reproduces this problem so we can get it sorted.

Thanks again.

**Comment by codedius** [comment]
Go env:

> GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/lepeshev/Library/Caches/go-build"
GOENV="/Users/lepeshev/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/lepeshev/Go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/lepeshev/Projects/Capodaster/capodaster-api/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3m/1j9pxct90c3cb0nrtvplb3c00000gn/T/go-build847069462=/tmp/go-build -gno-record-gcc-switches -fno-common"

Yes, I have `go 1.14` in `go.mod`

**Comment by pyorot** [comment]
Having the same problem. My local repository doesn't have a vendor folder (neither tracked nor untracked in Git); I have a simple go.mod:
```
module github.com/Pyorot/streams

go 1.14
// +heroku goVersion go1.14

require (
	github.com/bwmarrin/discordgo v0.20.2
	github.com/joho/godotenv v1.3.0
	github.com/nicklaw5/helix v0.5.7
)
```
This built fine in the default Go 1.12 (by deleting the goVersion line) but I get "go: inconsistent vendoring" error in 1.14, despite the readme of this project suggesting that vendoring shouldn't be used if the vendor directory is absent. It'd be convenient to have a +heroku comment to specify -mod=vendor vs -mod=readonly.

**Comment by danp** [comment]
Thank you both. I think I've reproduced the problem and found the issue, and I'll work on a proper fix. In the meantime, unless you need the [language change introduced in 1.14](https://golang.org/doc/go1.14#language), can you please try changing the `go 1.14` line in `go.mod` to `go 1.13`? I believe that will get it working. Note that you can keep the `// +heroku goVersion 1.14` line to use 1.14, the `go 1.14` line controls what language features are available.

Details on the issue, as I currently understand it:

Go 1.14 added [more consistency checks between go.mod and modules.txt and better defaulting of the mod flag](https://golang.org/doc/go1.14#vendor) which are activated with `go.mod` specifies `go 1.14` or higher. The buildpack has some catching up to do here and part of the issue is that it currently [calls go list with -mod=vendor](https://github.com/heroku/heroku-buildpack-go/blob/d8c4bd118ca00501fd7f3ec39c3764df0c6f48f6/bin/compile#L426) which can cause trouble when 1.14's new consistency checks are used.

**Comment by danp** [comment]
Hi,

I think I have a branch which fixes this. If you're up for trying it, read on. Otherwise, a fix should be pushed out in the next day or two. I'll update here when it's out.

To try the branch, use `heroku buildpacks:set` to change the Go buildpack's source. For example, if `heorku buildpacks` against your app only shows `heroku/go`, you can use `buildpacks:set` like so:

```
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-go.git#go-1-14-no-vendor
```

If `heroku buildpacks` shows a number of buildpacks including `heroku/go`, you can pass `-i` to `buildpacks:set` to set just the `heroku/go` entry. For example, if `heroku buildpacks` against your app shows something like:

```
=== my-app Buildpack URL
heroku/my-cool-buildpack
heroku/go
heroku/my-other-buildpack
```

You'd use `-i 2` to set `heroku/go`'s place in the list:

```
heroku buildpacks:set -i 2 https://github.com/heroku/heroku-buildpack-go.git#go-1-14-no-vendor
```

After using `buildpacks:set`, try pushing your app again. When using this branch, you can leave `go 1.14` in your `go.mod` file. When done testing, or once the fix is released (I'll update here when that happens), be sure to change back to `heroku/go` so your app doesn't unexpectedly break when this branch is deleted.

Thanks!

**Comment by pyorot** [comment]
Thanks for being on top of this. My fix was to set `// +heroku goVersion 1.12`. Won't have time to test the resolution but will be able to confirm that bumping it back to 1.14 works. Cheers

**Comment by beanieboi** [comment]
@danp i tried your branch and it worked for my project.

**Comment by codedius** [comment]
@danp any news when it's released?
