### ISSUE TITLE
Failed to compile Go app without vendor on Go 1.16 

### ISSUE THREAD

**Issue by darren** [heroku/heroku-buildpack-go#454]
go.mod
```
module test


// +heroku goVersion go1.16

go 1.16

require github.com/go-sql-driver/mysql v1.5.0
```

Push failed log:
```
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 382 bytes | 382.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-20 stack
remote: -----> Go app detected
remote: -----> Fetching stdlib.sh.v8... done
remote: -----> 
remote:        Detected go modules via go.mod
remote: -----> 
remote:        Detected Module Name: test
remote: -----> 
remote: -----> New Go Version, clearing old cache
remote: -----> Installing go1.16
remote: -----> Fetching go1.16.linux-amd64.tar.gz... done
remote: -----> Determining packages to install
remote:  !     Push rejected, failed to compile Go app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to darren-test-1.
remote: 
```

run[ this](https://github.com/heroku/heroku-buildpack-go/blob/d8c4bd118ca00501fd7f3ec39c3764df0c6f48f6/bin/compile#L426)  locally fails with error:

```
go list -find -mod=vendor -f '{{ if eq .Name "main" }} {{.ImportPath}} {{ end }}' ./...
go: inconsistent vendoring in /tmp/test:
	github.com/go-sql-driver/mysql@v1.5.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor
```

**Comment by danp** [comment]
Thanks. If you then run `go mod vendor` locally, does it change vendor/modules.txt? If so, can you please try committing those changes and pushing again?

**Comment by darren** [comment]
@danp 
Yes, run `go mod vendor` and commit vendor/modules.txt will make it compile successfully. But this is not necessary in previous versions.

**Comment by danp** [comment]
Could I please clarify what your situation was?

Was this a brand new app or were you updating it from a previous Go version to 1.16?

If updating, what Go version were you using before? What did the `go` line in go.mod say?

Did you have a vendor directory previously?

If you were updating from pre-1.14 to 1.16, the need to run `go mod vendor` again may be due to the changes mentioned under "Vendoring" here: https://golang.org/doc/go1.14#go-command. If you're using 1.14 or later and your go.mod has `go 1.14` or greater, there are more consistency checks done on vendor/modules.txt.

Thanks!

**Comment by darren** [comment]
Not reproducible on heroku now, I shall close it.
