### ISSUE TITLE
Use canonical import path if present

### ISSUE THREAD

**Issue by kr** [heroku/heroku-buildpack-go#63]
See http://tip.golang.org/doc/go1.4#canonicalimports

The canonical import path, if present in a package being built, should be used in preference to our existing sources of import path (`Godeps.json`, `.godir`).

**Comment by freeformz** [comment]
@kr I would assume that godep (or similar tooling) would DTRT when vendoring here instead of pushing this down to the build pack.

**Comment by kr** [comment]
Yes, godep should do the right thing. But this issue also has to do with projects that don't use godep. It used to be that, for such projects, the buildpack had no way to know the import path (which is why we defined the `.godir` convention). Now, the buildpack can check for a canonical import path magic comment.

Of the three possible ways to figure out the app's import path (`Godeps.json`, `.godir`, canonical import path), the canonical import path is the only one defined and approved by the Go team and used by stock go tooling that ships with the compiler. So I think if the canonical import path is present, it should be used.

**Comment by cyx** [comment]
Do you mean defining GOPATH as an environment variable and having the
buildpack read that?

**Comment by kr** [comment]
> Do you mean defining GOPATH as an environment variable and having the
> buildpack read that?

No, please see the link above for the definition of a canonical import path. This is about determining the base import path for the app. It is orthogonal to the choice of GOPATH.

**Comment by freeformz** [comment]
@kr My plan (pending some discussion and fact finding) is to remove support for non godep deploys, possibly adding in support for tools like https://github.com/kardianos/vendor and https://github.com/constabulary/gb as they become more feature complete.

**Comment by elithrar** [comment]
@freeformz Before I consider hacking on anything, have you started any work on making `gb build` (and/or also `gb-vendor`) an option for the buildpack?

**Comment by freeformz** [comment]
@elithrar Not as of yet as we've been focused on prepping some other stuff.

I'm happy to review your work when it's ready!

**Comment by kr** [comment]
Some more facts for your finding: this thread was revived today. https://groups.google.com/d/msg/golang-dev/74zjMON9glU/4lWCRDCRZg0J

If we're lucky, all the vendoring tools (and users thereof) will converge on this convention, and the buildpack will have only to run `go install -vendor ./...` and care not which vendoring tool was used. :grin: 

(Of course, that doesn't solve the issue of how to find the import path of the repo root, but this issue provides a pretty clear way to handle that: canonical import paths.)

**Comment by elithrar** [comment]
Yep, that's what prompted me to comment here! I'm thinking (with Go 1.5 in
mind) of the following changes:
- When Go 1.5 hits we test for the presence of a `/vendor` directory in the
  build dir and (if so) run `go install -vendor ./...` - should be able to
  drop it in ahead of the godeps checks in
  https://github.com/heroku/heroku-buildpack-go/blob/master/bin/compile#L58
  and other areas where we check for godeps today.
- Else we continue to either run godep or `go get` (if .godir exists) as
  per the present

That way, if a user is using (for example) gb-vendor it doesn't matter:
that's something for them to manage at a repo level. Heroku just accepts
the push and the buildpack detects the appropriate action. Since the
buildpack hardcodes the Go version there shouldn't be a need to do a
version check to determine if `go build -vendor` is safe either.

**Comment by kr** [comment]
In the spirit of being a little more on-topic, here is how to get the canonical import path, aka "import comment":

```
go list -f {{.ImportComment}}
```

**Comment by freeformz** [comment]
Please see #83. I haven't tested it yet.
/cc @cyx

**Comment by cyx** [comment]
Cool, will check in a few.

**Comment by freeformz** [comment]
Closing this in favor of #88
