### ISSUE TITLE
Support for gb 

### ISSUE THREAD

**Issue by fzerorubigd** [heroku/heroku-buildpack-go#84]
gb (https://github.com/constabulary/gb) is new tool to handle projects in go. gb is backward compatible and I use this build pack with normal go build, but it's good to have better support for gb.

**Comment by elithrar** [comment]
I just recently brought this up in another issue: https://github.com/heroku/heroku-buildpack-go/issues/63#issuecomment-111359322

Thus far I believe Heroku's plan is to wait until until Go 1.5 (July 31st) where we can call `GO15VENDOREXPERIMENT =1 go build .` to use the new vendoring behaviour:

> If there is a source directory d/vendor, then,
>     when compiling a source file within the subtree rooted at d,
>     import "p" is interpreted as import "d/vendor/p" if that exists.
> 
> When there are multiple possible resolutions,
>     the most specific (longest) path wins.
> 
> The short form must always be used: no import path can
>     contain “/vendor/” explicitly.

You can refer to these two CL's for some extra context:
- https://go-review.googlesource.com/#/c/10923/
- https://go-review.googlesource.com/#/c/11290/

**Comment by paxan** [comment]
I've created an independent [buildpack for gb.](https://github.com/paxan/heroku-buildpack-gb) It works for Go apps in our org. But I doubt it can be merged or mixed-in with this buildpack because `gb` misses some crucial stuff such as tags (last time I checked).

There was some brief convo about this in gb repo:
https://github.com/constabulary/gb/issues/85

**Comment by freeformz** [comment]
For now I've decided to support gb via https://hub.docker.com/r/heroku/go-gb/ (source: https://github.com/heroku/docker-go-gb)
